matrix:
  fast-finish: true
  include:
    - os: osx
      language: swift
      osx_image: xcode8
    - os: linux
      sudo: required
      dist: trusty
  allow_failures:
   - os: linux

install:
- if [[ $TRAVIS_OS_NAME == linux ]]; then wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then export SWIFT_VERSION=swift-3.0-GM-CANDIDATE; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then wget https://swift.org/builds/${SWIFT_VERSION}/ubuntu1404/${SWIFT_VERSION}/${SWIFT_VERSION}-ubuntu14.04.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then tar xzf ${SWIFT_VERSION}-ubuntu14.04.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then export PATH=${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:"${PATH}"; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then export PACKAGE_MANAGER_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then wget https://github.com/apple/swift-package-manager/archive/${PACKAGE_MANAGER_VERSION}.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then tar xzf ${PACKAGE_MANAGER_VERSION}.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then export PATH=${PWD}/${PACKAGE_MANAGER_VERSION}/usr/bin:"${PATH}"; fi
- if [[ $TRAVIS_OS_NAME == osx   ]]; then gem install xcpretty-travis-formatter; fi
script:
- if [[ $TRAVIS_OS_NAME == linux ]]; then swift package --version; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then swift build; fi
- if [[ $TRAVIS_OS_NAME == osx   ]]; then xcodebuild test -workspace Algorithms_and_Data_structures.xcworkspace -scheme Algorithms_and_Data_structures | xcpretty -f `xcpretty-travis-formatter` && export status=${PIPESTATUS[0]}; fi
- if [[ $TRAVIS_OS_NAME == osx   ]]; then bash <(curl -s https://codecov.io/bash); fi
- if [[ $TRAVIS_OS_NAME == osx   ]]; then exit ${status}; fi
