branches:
  only:
  - master
  - Development
language: objective-c
os: osx
osx_image: xcode8
install:
  - gem install xcpretty-travis-formatter
script:
  - xcodebuild test -workspace Algorithms-and-Data-structures.xcworkspace -scheme "Algorithms and Data structures" | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
