branches:
  only:
  - master
  - Development
language: objective-c
os: osx
osx_image: xcode8
script:
  - xcodebuild test -workspace Algorithms-and-Data-structures.xcworkspace -scheme "Algorithms and Data structures"
